### ISSUE TITLE
new lines

### ISSUE THREAD

**Issue by dustfeather** [Tiiffi/mcrcon#1]
The output does not know how to handle 'new line' characters. It displays all output on a single line.
Same on windows and linux.
I don't know C that well, but I think line 713 might be the problem.

**Comment by Tiiffi** [comment]
Some servers do not send newlines at all so this might be tricky to fix on the clientside.

Obvious fix would be to fix this on the serverside. Any other suggestions?

**Comment by dustfeather** [comment]
1.6.4

**Comment by dustfeather** [comment]
Well,  the client doesn't seem to have that problem :)

**Comment by Tiiffi** [comment]
This is known bug in minecraft vanilla server: **https://bugs.mojang.com/browse/MC-7569**

I could try to write some workaround hacks (if even possible) but I rather wait for proper fix for serverside before doing that.

**Comment by MaxMelehov** [comment]
@Tiffi, could you please add a command-line option to force new-line insertion in RCON. Vanilla MC server has this bug since 2013 and it seems it will never be fixed. So I know that it's better to fix it on serverside but we don't have such option. I believe this should be a simple change. No need to do any tricks to detect is RCON contains new-line or not. End user will specify it in command-line.

**Comment by Tiiffi** [comment]
> @Tiiffi could you please add a command-line option to force new-line insertion in RCON.

I am not sure how to do that.

Minecraft server is pushing out one big block of data without any new line markers. As far as I know it's impossible to detect where new lines should be.

Only thing I can do is to add workarounds for some command responses (like add newline before every '/' character when invoking "help" command).

**Comment by Tiiffi** [comment]
Commit https://github.com/Tiiffi/mcrcon/commit/bd76b897de4b73156195211632ba2772f154f24c attempts to fix this issue.
