### ISSUE TITLE
No Response Output on Custom rcon server

### ISSUE THREAD

**Issue by faervan** [Tiiffi/mcrcon#106]
Hey,

this might not be an issue with mcrcon but maybe rather a help request regarding the rcon specification, but I'm not sure...

I just made a little custom rcon server in rust following [valve's specification](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol#Multiple-packet_Responses), but when I try mcrcon with my server mcrcon doesn't output my response bodies. [rcon-cli](https://github.com/gorcon/rcon-cli) does that just fine tho.
When using mcrcon with my VRising server the output works just fine and with Minecraft as well.

The packets send back and forth:
```
// Authentication
server received bytes: [13, 0, 0, 0, 222, 192, 173, 11, 3, 0, 0, 0, 97, 98, 99, 0, 0]
server received Packet: Packet {
    id: 195936478,
    packet_type: ServerdataAuth,
    body: "abc",
}

// Empty SERVERDATA_RESPONSE_VALUE
server sends bytes: [10, 0, 0, 0, 222, 192, 173, 11, 0, 0, 0, 0, 0, 0]
// Authentication success
server sends response: Packet {
    id: 195936478,
    packet_type: ServerdataAuthResponse,
    body: "",
}
server sends bytes: [10, 0, 0, 0, 222, 192, 173, 11, 2, 0, 0, 0, 0, 0]

// Receiving the command
server received bytes: [14, 0, 0, 0, 222, 192, 173, 11, 2, 0, 0, 0, 112, 105, 110, 103, 0, 0]
server received Packet: Packet {
    id: 195936478,
    packet_type: ServerdataExeccommand,
    body: "ping",
}

// Sending Response
server sends response: Packet {
    id: 195936478,
    packet_type: ServerdataResponseValue,
    body: "pong",
}
server sends bytes: [14, 0, 0, 0, 222, 192, 173, 11, 0, 0, 0, 0, 112, 111, 110, 103, 0, 0]

Client aborted the tcp connection
```

Mcrcon doesn't print out pong:
```
$ mcrcon -H 127.0.0.1 -P 27015 -p abc ping
$
```

rcon-cli does:
```
$ rcon -a 127.0.0.1:27015 -p abc ping
pong
$
```

**Comment by Tiiffi** [comment]
Hi,

Mcrcon was originally modelled after vanilla Minecrafts rcon implementation & behaviour so there are some snags and incompatibilities with other rcon implementations. Currently mcrcon doesn't even support multipacket responses.

Rcon protocol implementations are actually quite a mess across different servers.  It seems that every other server has some variation in the implementation details (Ark, Project Zomboid, Rust, Conan Exiles, Valve, Minecraft, Palworld, V Rising etc).

---

As for this exact problem I probably know what is happening. Valve server sends empty **RCON_RESPONSE_VALUE** packet before actual **RCON_AUTH_RESPONSE** packet.
Minecraft doesn't do this and mcrcon is not handling the empty **RCON_RESPONSE_VALUE** packet correctly so it "drops out of sync".

I have some unpublished work in progress "librcon" code which should be handling this case:
```c
// auth exchange

switch (packet.type) {
        case RCON_RESPONSE_VALUE:
                // valve "garbage packet" so try to receive real response
                goto receive_packet;
        break;

        case RCON_AUTH_RESPONSE:
                // NOTE: should probably check packet id too
                rcon->status = rcon_ok;
        break;
}

```
---

ps. Is your custom Rust rcon server available somewhere?

I could probably use it for testing my client code instead of running multiple different rcon implementations which requires downloading gigabytes of server data from Steam (not to mention setting the servers up). 😖🫠

**Comment by faervan** [comment]
> Hi,

Hey, thanks for your response :)

> ps. Is your custom Rust rcon server available somewhere?

Yes, it is! [Here](https://github.com/Faervan/yggdrasil/blob/main/crates/rcon-server/src/lib.rs)
If you have [rust](https://rustup.rs/) installed, you can just go into the `rcon-server` directory and run `cargo run --example server`

As mentioned, I just followed valves specification. So if the empty RCON_RESPONSE_VALUE packet is the only issue I also could just leave this packet out and hope other clients like `rcon-cli` do accept this as well.

But if your implementation could handle the packet, it would be great :)

**Comment by Tiiffi** [comment]
> Yes, it is! [Here](https://github.com/Faervan/yggdrasil/blob/main/crates/rcon-server/src/lib.rs) If you have [rust](https://rustup.rs/) installed, you can just go into the `rcon-server` directory and run `cargo run --example server`

Thanks, I'll check it out.

> So if the empty RCON_RESPONSE_VALUE packet is the only issue I also could just leave this packet out and hope other clients like `rcon-cli` do accept this as well.

In my opinion you should keep it as close as possible to Valve rcon since it's pretty much the reference implementation. It's clients task to handle protocol variation (I wish there was "protocol version" field or something 🤔).

Of course there could be a option to change the mode to conform vanilla Minecraft behaviour though (no extra packet, no multipacket responses).

>But if your implementation could handle the packet, it would be great :)

I will probably try to fix this to next version before I switch using my new version of the rcon lib.

**Comment by faervan** [comment]
> Of course there could be a option to change the mode to conform vanilla Minecraft behaviour though (no extra packet, no multipacket responses).

I did that, now it works just fine. Thanks for your help.

> I will probably try to fix this to next version before I switch using my new version of the rcon lib.

I will leave this open then.

**Comment by Tiiffi** [comment]
Hi,

I modified the code to support Valve style authenticationa and pushed new Develop branch online: https://github.com/Tiiffi/mcrcon/tree/Develop

If  possible could you try if it works as expected?

**Comment by faervan** [comment]
> Hi,
> 
> I modified the code to support Valve style authenticationa and pushed new Develop branch online: https://github.com/Tiiffi/mcrcon/tree/Develop
> 
> If possible could you try if it works as expected?

Sure, will do this tomorrow.

**Comment by faervan** [comment]
Works now! Thx for your effort :)

**Comment by Tiiffi** [comment]
Cool, closing this now.

Thank you for helping!
