### ISSUE TITLE
Is the author Tiiffi still in GitHub?

### ISSUE THREAD

**Issue by Hagb** [Tiiffi/mcrcon#22]
Is the author @Tiiffi still in GitHub?

**Comment by carlbennett** [comment]
Second this. There's 28 forks and I don't know which one to trust or which is better. I support a more wholesome repository that takes the changes from its downstream and merges them upstream.

**Comment by Hagb** [comment]
@carlbennett Does "second this" mean that this account (carlbennett) is the second account of Tiiffi?

**Comment by carlbennett** [comment]
Do I look like I am the "second account"? No.

**Comment by Hagb** [comment]
Sorry... I am bad at English

**Comment by carlbennett** [comment]
My apologies, I can be a bit terse. Anyway, I'm not sure where @Tiiffi ran off to. This repository hasn't been updated in years. The forks are where updates have been. I took time last night to make mine full and wholesome with a newer Readme, merged code from #20, and merged `develop` into `master` since it's functional and I feel is safe to release. Since I'm not the repository source, I cannot make binaries available on GitHub, however.

**Comment by terokorp** [comment]
I know Tiiffi, he hasn't use github for long time.
I sent a message for him if I can get write permission to this repo or if he can move it for me.
At the beginning, it was me who requested this software and he made it for me.

**Comment by sabatech** [comment]
I attempted to submit the fixed source that a friend worked on, I hope it saved and also hope it works for others. It works like a charm for me.

**Comment by sabatech** [comment]
https://pastebin.com/cPLurUh1 I am not sure if my file made it on here, and I am no programmer and not used to working with sourceforge... If anyone is interested I posted it here:
https://pastebin.com/cPLurUh1

**Comment by terokorp** [comment]
I just got permissions to this project and merged pull request that @Hagb was sent. Now color codes seems to work.
