### ISSUE TITLE
Always returns exit code 1

### ISSUE THREAD

**Issue by Programie** [Tiiffi/mcrcon#29]
Every command executed results in mcrcon returning exit code 1 instead of 0 independent whether the command succeeded or not.

I've tested it with the following servers:

* Spigot with Minecraft 1.12.2
* Spigot with Minecraft 1.14.4
* Forge with Minecraft 1.12.2
* Forge with Minecraft 1.14.4

**Comment by Tiiffi** [comment]
There is no protocol level way to detect if the command succeeded or not. I will probably default the return value to EXIT_SUCCESS for next release.

There is a possibility to check the content of server response and then return appropriate exit code (e.g. string compare to check if response includes "_Unknown command_" substring etc.).

The problem is that different server versions might use different responses for these situations.

Any good suggestions how to handle this?

**Comment by Programie** [comment]
If it is not possible to check whether the command succeeded, it might be better to simply always return EXIT_SUCCESS (exit code 0).

Exit code 1 might be suitable for protocol issues or a failed login (if there is some way to detect that).
