### ISSUE TITLE
no returns from localhost

### ISSUE THREAD

**Issue by korvyr** [Tiiffi/mcrcon#35]
When connecting to localhost, it will send commands just fine, but will not show any returns.

**Comment by Tiiffi** [comment]
Hi,

What commands you are sending?
What version mcrcon you are using (check with `mcrcon -v`)?
What version minecraft server you are using?

**Comment by davidbdeath** [comment]
I'm having the same problem

**Comment by Diamondtroller** [comment]
I think @korvyr  meant that he doesn't have server output in cmd windows.
@Tiiffi Is output of server even supported?
I think that there isn't chat thread output and server thread output available.
Or is it a bug?

**Comment by Tiiffi** [comment]
@davidbdeath 
- What command-line options you are using?
- Does this happen with every command?
- What version of Minecraft server you are using?
- What version of mcrcon you are using?



@Diamondtroller 
>Is output of server even supported?

Currently Minecraft servers are not sending messages such as game chat etc. via rcon connection.
Server sends response only when command is invoked via rcon.

This behaviour follows [Source RCON Protocol](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol).

**Comment by tmanifold** [comment]
@Diamondtroller 
> Is output of server even supported?
From my (very basic) understanding of how Minecraft server and RCON work, this sort of functionality requires a wrapper around the server that can read its output and send it to the client.

**Comment by davidbdeath** [comment]
I stopped using mcrcon and installed screens on my vm. I was using Minecraft version is 1.15.2 and whatever was the current version of mcrcon and spigotMC.

mcrcon will return the first like over ssh. For example mcrcon list will return how many users are online but not the names of the users. The end of the line has [0m appended.
I noticed it when trying to use lp editor and the link lucky perms generates wasn’t returned. It would be easier to use mcrcon instead of screens to interact with the server on my phone.

**Comment by Tiiffi** [comment]
I am still note quote sure what is going on here.

Any video or screenshots of these problems happening?

@davidbdeath 
> For example mcrcon list will return how many users are online but not the names of the users. The end of the line has [0m appended.

What ihapens if you start mcrcon with `-c`flag which disables color printing?
Also what happens if you use `-r` flag to print raw messages?

**Comment by Tiiffi** [comment]
Closing because I have no idea what the actual problem is.
